### ISSUE TITLE
Have problems compiling it.

### ISSUE THREAD

**Issue by upgradeQ** [Xyene/type-mania#1]
This game seems interesting, how do I compile it? (not java user here )

**Comment by Xyene** [comment]
I don't actually remember, it's been 3 years 😅 

You'll probably need Maven to compile it, but I don't have details on that anymore, nor any idea if the `pom.xml` works.

I do however have compiled binaries and some mapped songs from when I was working on this, if you're interested:

* Compiled game: https://www.dropbox.com/sh/n102xcsnb2npkti/AAAfmxXyDrY3nCJqdIlApFVPa/type%21mania.jar?dl=0 
* Songs: https://www.dropbox.com/sh/n102xcsnb2npkti/AAB0WxsRvBFdGYKu7Kcld7OPa/songs?dl=0 (should be in a folder called `songs` in the same directory as `type!mania.jar`)

The Ylvis map is doable, though I may have gone overboard on the Row, Row, Row Your Boat... I've never been able to pass it, nor has anyone I know 😁
